---

- name: Downloading the repo jenkins
  get_url:
    url: "{{jenkins.URL}}"
    dest: "{{jenkins.Destination}}"
  become: true

- name: Imporying the GPG Key
  rpm_key:
    state: present
    key: "{{jenkins.GPG_Key}}"

- name: Installing Jenkins
  yum:
    name: jenkins
    state: present

- name: start the jenkins server and enable on boot
  service:
    name: jenkins
    state: started
    enable: yes

- name: open management console port
  firewalld:
    port=8080/tcp
    zone=public
    permanent=true
    state=enabled
    immediate=yes

- name: open management console port
  firewalld:
    service=http
    zone=public
    permanent=true
    state=enabled
    immediate=yes
