---

- name: Downloading the repo jenkins
  get_url:
    url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Imporying the GPG Key
  rpm_key:
    state: present
    key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Installing Jenkins
  yum:
    name: jenkins
    state: present

- name: start the jenkins server and enable on boot
  service:
    name: jenkins
    state: started
    enable: yes

- name: open management console port
  firewalld:
    port=8080/tcp
    zone=public
    permanent=true
    state=enabled
    immediate=yes

- name: open management console port
  firewalld:
    service=http
    zone=public
    permanent=true
    state=enabled
    immediate=yes
