---

- name: Creates directory
  file: path=~/NGINX_LUA state=directory

- name: Upload the nginx update file
  copy: src= dest=~/NGINX_LUA/ mode=0644

- name: change the file permission
  file:
    path: ~/NGINX_LUA/
    mode: 0755

- name: stop nginx server
  service:
    name: dmc_nginx
    pattern: /opt/pace/nginx/bin/dmc_nginx
    state: stopped

- name: archive files on serverA
  shell: tar -czvf nginx1.8.0.bu.`date +\%m\%d\%y`.tar.gz -C /opt/pace/nginx .
    args:
      chdir: ~/NGINX_LUA/BACKUP/
    tags: release

- name: Creates directory
  file: path=~/NGINX_LUA/BACKUP/conf.d/ state=directory

- name: Creates directory
  file: path=~/NGINX_LUA/BACKUP/bin/ state=directory

- name: Upload the nginx update file
  copy: src=/opt/pace/nginx/conf.d/. dest=~/NGINX_LUA//BACKUP/conf.d/

- name: Upload the nginx update file
  copy: src=/opt/pace/nginx/bin/dmc_nginx dest=~/NGINX_LUA/BACKUP/bin/

- name: Ansible check file exists.
    stat:
      path: ~/NGINX_LUA/BACKUP/bin
    register: p
  - debug:
      msg: "File exists in bin"
    when: p.stat.exists

- name: Ansible check file exists.
    stat:
      path: ~/NGINX_LUA/BACKUP/conf.d
    register: p
  - debug:
      msg: "File exists in config.d"
    when: p.stat.exists
