---

- name: Installing java
  yum:
    name: java-1.8.0-openjdk
    state: latest
  become: true

- name: Changing the default java verion
  alternatives:
    name: java
    link: /bin/java
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/jre/bin/java
